* TODO install stack in Docker
asking Reddit: http://www.reddit.com/r/haskellquestions/comments/a10cs7/how_to_add_stack_to_a_docker_environment/
for a history of my attempts: see github/jeff/tax.co, branch "install-stack"
* rules look lke this
** this
<pattern> %> \out -> do
    <actions>
(where the angle brackets aren't missing)
** Whatever matches "pattern" is bound to "out" in the lambda.
* use fewer calls to need, if possible
** how: make the list argument to "need" longer
rather than calling it more than once in the same do-expression
** why: "multiple files required by a need can be built in parallel"
* avoid circularities
"You should only use getDirectoryFiles on source files, not files that are generated by the build system, otherwise the results will change while you are running the build and the build may be inconsistent."
* TODO `phony` is confusing to me
https://shakebuild.com/manual
* cmd_
** takes any number of space-separated args
cmd_ "gcc -o _make/run _build/main.o _build/constants.o"
cmd_ ["gcc","-o","_make/run","_build/main.o","_build/constants.o"]
** enclose unknown strings in []s
 "[For cmd_ to] properly handle unknown string variables it is recommended to enclose them in a list, e.g. [out], so that even if out contains a space it will be treated as a single argument."
* some string operators
** // is like * for paths
*** "The * wildcard matches anything apart from a directory separator. For example "manual/*.txt" would define a rule for any .txt file in the manual directory, including manual/examples.txt, but would not match manual/examples.zip, examples.txt or manual/docs/examples.txt."
*** "The // wildcard matches any number of complete path components. For example //*.txt would define a rule for any .txt file, including manual/examples.txt."
** `<.> exe` adds an extension if OS-appropriate
** use -<.> to strip an extension and replace it
*** TODO What if there are multiple dots in the name?
